### ISSUE TITLE
compilation warnings of  stencil_oddc_metadirective.c

### ISSUE THREAD

**Issue by chunhualiao** [ouankou/whiteboard#1]
stencil_oddc_metadirective.c:471:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
stencil_oddc_metadirective.c:503:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
2 warnings generated.
stencil_oddc_metadirective.c:471:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
stencil_oddc_metadirective.c:503:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
2 warnings generated.

**Comment by ouankou** [comment]
The latest code has been moved to https://github.com/chunhualiao/homp-metadirective/blob/master/stencil_metadirective_online.c
The issue is fixed there.
