### ISSUE TITLE
include the data allocation and transfer time in total time

### ISSUE THREAD

**Issue by chunhualiao** [ouankou/whiteboard#2]
when you measure the cpu vs. gpu total time, do you also include the data allocation and transfer time?
I think counting them is important to have a fair comparison.
 
This also is related to your models (considering costs to prepare data).

**Comment by ouankou** [comment]
The latest code has been moved to https://github.com/chunhualiao/homp-metadirective/blob/master/stencil_metadirective_online.c

The data allocation and transfer between host and GPU are included in the GPU computing function. Thus, the time cost is part of the measured total time cost.
https://github.com/chunhualiao/homp-metadirective/blob/fcdb93b44006a529ba8f21a1940fff7102ca65b9/stencil_metadirective_online.c#L256
